projects:
  webmdgraph:
    schemaPath: amplify/backend/api/webmdgraph/build/schema.employees
    includes:
      - src/employees/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/employees
extensions:
  amplify:
    version: 3
