export const CRUD_ACTION_GET_LIST = "CRUD_ACTION_GET_LIST";
export const CRUD_ACTION_DELETE_ENTITY = "CRUD_ACTION_DELETE_ENTITY";
export const CRUD_ACTION_UPDATE_ENTITY = "CRUD_ACTION_UPDATE_ENTITY";
export const CRUD_ACTION_SUBSCRIBE_NEW_ENTITY =
  "CRUD_ACTION_SUBSCRIBE_NEW_ENTITY";
export const CRUD_ACTION_SUBSCRIBE_UPDATED_ENTITY =
  "CRUD_ACTION_SUBSCRIBE_UPDATED_ENTITY";
export const CRUD_ACTION_SUBSCRIBE_DELETED_ENTITY =
  "CRUD_ACTION_SUBSCRIBE_DELETED_ENTITY";
export const CRUD_ACTION_CREATE_ENTITY = "CRUD_ACTION_CREATE_ENTITY";
export const CRUD_MUTATION_STORE_LIST = "CRUD_MUTATION_STORE_LIST";
export const CRUD_MUTATION_NEW_ENTITY = "CRUD_MUTATION_NEW_ENTITY";
export const CRUD_MUTATION_UPDATED_ENTITY = "CRUD_MUTATION_UPDATED_ENTITY";
export const CRUD_MUTATION_DELETED_ENTITY = "CRUD_MUTATION_DELETED_ENTITY";
