// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_appsync_graphqlEndpoint:
    "https://qcqcnmr5azdj7mz32ulksutt4u.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AWS_IAM",
  aws_content_delivery_bucket:
    "webmd-web-app-20191216181919-hostingbucket-develop",
  aws_content_delivery_bucket_region: "us-east-1",
  aws_content_delivery_url:
    "http://webmd-web-app-20191216181919-hostingbucket-develop.s3-website-us-east-1.amazonaws.com"
};

export default awsmobile;
